name: Cargo Build & Test

on:
  push:
  pull_request:

env: 
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Rust project - latest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v3
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: rustup component add rustfmt
      - run: cd crate
      - run: cargo fmt -- --check
      - run: cargo clippy --all-targets --all-features -- -D warnings -D clippy::pedantic -D clippy::cargo
      - run: cargo build --verbose
      - run: cargo test --verbose