name: Cargo Build & Test

on:
  push:
  pull_request:

env: 
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Rust project - latest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - uses: actions/checkout@v3
      - name: Setup Rust
        run: |
          rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
          rustup component add rustfmt
      - name: Install cargo-nextest
        uses: baptiste0928/cargo-install@v1
        with:
          crate: cargo-nextest
          locked: true
      - name: Check Format
        run: |
          cd crate
          cargo fmt -- --check
      - name: Clippy Lint Checks
          cd crate
          cargo clippy --all-targets --all-features -- -D warnings -D clippy::pedantic -D clippy::cargo
      - name: Build
        run: |
          cd crate
          cargo build --verbose
      - name: Build docs
        run: |
          cd crate
          cargo doc -r --no-deps
      - name: Run Doc Tests
        run: |
          cd crate
          cargo test --doc
      - name: Run Tests
        run: |
          cd crate
          cargo nextest run